### ISSUE TITLE
JAVA: 1.4 Método ejecutarOpciones() -> Parte 1 y 2

### ISSUE THREAD

**Issue by aniascua** [CodeSystem2022/Hellfish_4to_semestre#26]
Links a videos:

1. https://drive.google.com/file/d/1x4WtUE9rLGysURFx17xIJ_FTypc2HF8M/view?usp=drive_link

2. https://drive.google.com/file/d/1PgvQ3BIz1CqxBsmolBDPJy_ulhYIsIvn/view?usp=drive_link

**Comment by FrancoFB** [comment]
Reasignado por que no se hizo
